eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka
    register-with-eureka: true


management:
  endpoints:
    web:
      exposure:
        include: "*"

  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans


spring:
  kafka:
    bootstrap-servers: kafka:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    properties:
      spring:
        json:
          add:
            type:
              headers: false