server:
  port: 8084

spring:
  datasource:
    username: chinmayanand
    password: admin

  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: 1CHN1Bi8R0YYkCN6mrDEcys4HHAK3RJqU/1Alp+B1Xg=
  expiration: 3600000