server:
  port: 8084

spring:
  datasource:
    username: chinmayanand
    password: admin

  jpa:
    hibernate:
      ddl-auto: update

  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}