
spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:postgresql://localhost:5432/customer_db
    username: chinmayanand
    password: admin

server:
    port: 8081

eureka:
  client:
   - service-url:
      defaultZone: http://localhost:8761/eureka
   - register-with-eureka:  true