spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/transaction_db

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    properties:
      spring:
        json:
          add:
            type:
              headers: false
